name: Lint

on:
  workflow_dispatch:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Build And Test Frontend
        run: |
          cd frontend
          npm ci
          npm run lint
